#ifndef MOUSEWHEEL_DEFINITIONS_H
#define MOUSEWHEEL_DEFINITIONS_H

#define PIN_WHEEL_TASK_ACTIVE 20
#define PIN_TUD_TASK_ACTIVE 21
#define PIN_HID_TASK_ACTIVE 22
#define PIN_LED_BLINKING_TASK_ACTIVE 26

// tasks
#define INTERVAL_MS_UPDATE_MOUSEWHEEL_TASK 1

// mousewheel
#define MOUSEWHEEL_ANGLE_FILTER_WINDOW_SIZE 20 // max 255


#endif